// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-Di6t8QSqaiv5Rfg-OjS_cAb-KlC5VjY',
    appId: '1:420810891567:web:86f6c9bdc3e2034e5601da',
    messagingSenderId: '420810891567',
    projectId: 'travelduck-2c225',
    authDomain: 'travelduck-2c225.firebaseapp.com',
    storageBucket: 'travelduck-2c225.firebasestorage.app',
    measurementId: 'G-9VEZ5GLB1Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOWR7TYWXMyphJSNeH_a8Ku2kTFJZvQNs',
    appId: '1:420810891567:android:b6eb1aa4e36516555601da',
    messagingSenderId: '420810891567',
    projectId: 'travelduck-2c225',
    storageBucket: 'travelduck-2c225.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7roG3_SYXV70aLqGZuHFL4Ls3aUz39RY',
    appId: '1:420810891567:ios:8a9b1b736041f1235601da',
    messagingSenderId: '420810891567',
    projectId: 'travelduck-2c225',
    storageBucket: 'travelduck-2c225.firebasestorage.app',
    iosBundleId: 'com.example.travelBee',
  );
}
